//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceActiveDirectory
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaSeguridadM", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Seguridad")]
    public partial class RespuestaSeguridadM : object
    {
        
        private ServiceActiveDirectory.Cls_Ent_Auditoria AuditoriaField;
        
        private ServiceActiveDirectory.Cls_Ent_Sistemas_Modulos[] ModulosField;
        
        private string ModulosHtmlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_Auditoria Auditoria
        {
            get
            {
                return this.AuditoriaField;
            }
            set
            {
                this.AuditoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_Sistemas_Modulos[] Modulos
        {
            get
            {
                return this.ModulosField;
            }
            set
            {
                this.ModulosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModulosHtml
        {
            get
            {
                return this.ModulosHtmlField;
            }
            set
            {
                this.ModulosHtmlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cls_Ent_Auditoria", Namespace="http://schemas.datacontract.org/2004/07/Capa_Entidad")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_Persona))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_PersonaExterna))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_PersonaRepresentante))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_Oficina[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_Oficina))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_Sistemas_Modulos[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_Sistemas_Modulos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_Base))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_Usuario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_Perfil[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_Perfil))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_Solicitud_Usuario_Login))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.RespuestaSeguridadM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.RespuestaSeguridadU))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.RespuestaAuditoria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.RespuestaSeguridadID))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.RespuestaSeguridadBool))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.SeguridadArchivo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.RespuestaPerfil))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.RespuestaOficina))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.RespuestaSolicitudLogin))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.RespuestaSolicitudLoginRegistro))]
    public partial class Cls_Ent_Auditoria : object
    {
        
        private bool AUTORIZADOField;
        
        private bool EJECUCION_PROCEDIMIENTOField;
        
        private string ERROR_LOGField;
        
        private string MENSAJE_SALIDAField;
        
        private object OBJETOField;
        
        private object OBJETO2Field;
        
        private bool RECHAZARField;
        
        private string URLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AUTORIZADO
        {
            get
            {
                return this.AUTORIZADOField;
            }
            set
            {
                this.AUTORIZADOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EJECUCION_PROCEDIMIENTO
        {
            get
            {
                return this.EJECUCION_PROCEDIMIENTOField;
            }
            set
            {
                this.EJECUCION_PROCEDIMIENTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERROR_LOG
        {
            get
            {
                return this.ERROR_LOGField;
            }
            set
            {
                this.ERROR_LOGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MENSAJE_SALIDA
        {
            get
            {
                return this.MENSAJE_SALIDAField;
            }
            set
            {
                this.MENSAJE_SALIDAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object OBJETO
        {
            get
            {
                return this.OBJETOField;
            }
            set
            {
                this.OBJETOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object OBJETO2
        {
            get
            {
                return this.OBJETO2Field;
            }
            set
            {
                this.OBJETO2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RECHAZAR
        {
            get
            {
                return this.RECHAZARField;
            }
            set
            {
                this.RECHAZARField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL
        {
            get
            {
                return this.URLField;
            }
            set
            {
                this.URLField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cls_Ent_Sistemas_Modulos", Namespace="http://schemas.datacontract.org/2004/07/Capa_Entidad")]
    public partial class Cls_Ent_Sistemas_Modulos : ServiceActiveDirectory.Cls_Ent_Base
    {
        
        private string DESC_MODULOField;
        
        private string DESC_TIPO_MODULOField;
        
        private string ID_AField;
        
        private string ID_LIField;
        
        private string ID_PERFILField;
        
        private int ID_SISTEMAField;
        
        private int ID_SISTEMA_MODULOField;
        
        private int ID_SISTEMA_MODULO_PADREField;
        
        private int ID_TIPO_MODULOField;
        
        private long ID_USUARIOField;
        
        private string IMAGENField;
        
        private ServiceActiveDirectory.Cls_Ent_Sistemas_Modulos[] Modulos_HijosField;
        
        private int NIVELField;
        
        private int ORDENField;
        
        private string URL_MODULOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESC_MODULO
        {
            get
            {
                return this.DESC_MODULOField;
            }
            set
            {
                this.DESC_MODULOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESC_TIPO_MODULO
        {
            get
            {
                return this.DESC_TIPO_MODULOField;
            }
            set
            {
                this.DESC_TIPO_MODULOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_A
        {
            get
            {
                return this.ID_AField;
            }
            set
            {
                this.ID_AField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_LI
        {
            get
            {
                return this.ID_LIField;
            }
            set
            {
                this.ID_LIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_PERFIL
        {
            get
            {
                return this.ID_PERFILField;
            }
            set
            {
                this.ID_PERFILField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_SISTEMA
        {
            get
            {
                return this.ID_SISTEMAField;
            }
            set
            {
                this.ID_SISTEMAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_SISTEMA_MODULO
        {
            get
            {
                return this.ID_SISTEMA_MODULOField;
            }
            set
            {
                this.ID_SISTEMA_MODULOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_SISTEMA_MODULO_PADRE
        {
            get
            {
                return this.ID_SISTEMA_MODULO_PADREField;
            }
            set
            {
                this.ID_SISTEMA_MODULO_PADREField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TIPO_MODULO
        {
            get
            {
                return this.ID_TIPO_MODULOField;
            }
            set
            {
                this.ID_TIPO_MODULOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID_USUARIO
        {
            get
            {
                return this.ID_USUARIOField;
            }
            set
            {
                this.ID_USUARIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMAGEN
        {
            get
            {
                return this.IMAGENField;
            }
            set
            {
                this.IMAGENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_Sistemas_Modulos[] Modulos_Hijos
        {
            get
            {
                return this.Modulos_HijosField;
            }
            set
            {
                this.Modulos_HijosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NIVEL
        {
            get
            {
                return this.NIVELField;
            }
            set
            {
                this.NIVELField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ORDEN
        {
            get
            {
                return this.ORDENField;
            }
            set
            {
                this.ORDENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL_MODULO
        {
            get
            {
                return this.URL_MODULOField;
            }
            set
            {
                this.URL_MODULOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cls_Ent_Persona", Namespace="http://schemas.datacontract.org/2004/07/Capa_Entidad.Bitacora")]
    public partial class Cls_Ent_Persona : object
    {
        
        private string CORREO_INSTITUCIONAL_PERSONAField;
        
        private string CORREO_PERSONAL_PERSONAField;
        
        private string ID_PERSONAField;
        
        private string NOMBRE_PERSONAField;
        
        private string NRO_DOC_PERSONAField;
        
        private string TIPO_DOC_PERSONAField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO_INSTITUCIONAL_PERSONA
        {
            get
            {
                return this.CORREO_INSTITUCIONAL_PERSONAField;
            }
            set
            {
                this.CORREO_INSTITUCIONAL_PERSONAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO_PERSONAL_PERSONA
        {
            get
            {
                return this.CORREO_PERSONAL_PERSONAField;
            }
            set
            {
                this.CORREO_PERSONAL_PERSONAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_PERSONA
        {
            get
            {
                return this.ID_PERSONAField;
            }
            set
            {
                this.ID_PERSONAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE_PERSONA
        {
            get
            {
                return this.NOMBRE_PERSONAField;
            }
            set
            {
                this.NOMBRE_PERSONAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRO_DOC_PERSONA
        {
            get
            {
                return this.NRO_DOC_PERSONAField;
            }
            set
            {
                this.NRO_DOC_PERSONAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_DOC_PERSONA
        {
            get
            {
                return this.TIPO_DOC_PERSONAField;
            }
            set
            {
                this.TIPO_DOC_PERSONAField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cls_Ent_PersonaExterna", Namespace="http://schemas.datacontract.org/2004/07/Capa_Entidad.Bitacora")]
    public partial class Cls_Ent_PersonaExterna : ServiceActiveDirectory.Cls_Ent_Base
    {
        
        private string APELLIDO_MATERNOField;
        
        private string APELLIDO_PATERNOField;
        
        private string CELULARField;
        
        private string CLAVEField;
        
        private string CODIGO_DNIField;
        
        private string CODIGO_UBIGEO_DNIField;
        
        private string CODIGO_VERIFICA_DNIField;
        
        private string CORREOField;
        
        private string DIRECCIONField;
        
        private string DNIField;
        
        private string FECHA_NACIMIENTOField;
        
        private string FLG_DECLARACIONField;
        
        private string FLG_TERMINOField;
        
        private string FLG_VALIDOField;
        
        private string ID_DEPARTAMENTOField;
        
        private string ID_DISTRITOField;
        
        private int ID_LFField;
        
        private string ID_PAISField;
        
        private string ID_PERSONAField;
        
        private string ID_PROVINCIAField;
        
        private int ID_SISTEMAField;
        
        private string ID_TIPO_DOCUMENTOField;
        
        private string ID_TIPO_PERSONAField;
        
        private int ID_TIPO_USUARIOField;
        
        private string NOMBRESField;
        
        private string OBSERVACIONField;
        
        private string RAZON_SOCIALField;
        
        private string RUCField;
        
        private ServiceActiveDirectory.Cls_Ent_PersonaRepresentante RepresentanteLegalField;
        
        private string TELEFONOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APELLIDO_MATERNO
        {
            get
            {
                return this.APELLIDO_MATERNOField;
            }
            set
            {
                this.APELLIDO_MATERNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APELLIDO_PATERNO
        {
            get
            {
                return this.APELLIDO_PATERNOField;
            }
            set
            {
                this.APELLIDO_PATERNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CELULAR
        {
            get
            {
                return this.CELULARField;
            }
            set
            {
                this.CELULARField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLAVE
        {
            get
            {
                return this.CLAVEField;
            }
            set
            {
                this.CLAVEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_DNI
        {
            get
            {
                return this.CODIGO_DNIField;
            }
            set
            {
                this.CODIGO_DNIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_UBIGEO_DNI
        {
            get
            {
                return this.CODIGO_UBIGEO_DNIField;
            }
            set
            {
                this.CODIGO_UBIGEO_DNIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_VERIFICA_DNI
        {
            get
            {
                return this.CODIGO_VERIFICA_DNIField;
            }
            set
            {
                this.CODIGO_VERIFICA_DNIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO
        {
            get
            {
                return this.CORREOField;
            }
            set
            {
                this.CORREOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DIRECCION
        {
            get
            {
                return this.DIRECCIONField;
            }
            set
            {
                this.DIRECCIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI
        {
            get
            {
                return this.DNIField;
            }
            set
            {
                this.DNIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHA_NACIMIENTO
        {
            get
            {
                return this.FECHA_NACIMIENTOField;
            }
            set
            {
                this.FECHA_NACIMIENTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FLG_DECLARACION
        {
            get
            {
                return this.FLG_DECLARACIONField;
            }
            set
            {
                this.FLG_DECLARACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FLG_TERMINO
        {
            get
            {
                return this.FLG_TERMINOField;
            }
            set
            {
                this.FLG_TERMINOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FLG_VALIDO
        {
            get
            {
                return this.FLG_VALIDOField;
            }
            set
            {
                this.FLG_VALIDOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_DEPARTAMENTO
        {
            get
            {
                return this.ID_DEPARTAMENTOField;
            }
            set
            {
                this.ID_DEPARTAMENTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_DISTRITO
        {
            get
            {
                return this.ID_DISTRITOField;
            }
            set
            {
                this.ID_DISTRITOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_LF
        {
            get
            {
                return this.ID_LFField;
            }
            set
            {
                this.ID_LFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_PAIS
        {
            get
            {
                return this.ID_PAISField;
            }
            set
            {
                this.ID_PAISField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_PERSONA
        {
            get
            {
                return this.ID_PERSONAField;
            }
            set
            {
                this.ID_PERSONAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_PROVINCIA
        {
            get
            {
                return this.ID_PROVINCIAField;
            }
            set
            {
                this.ID_PROVINCIAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_SISTEMA
        {
            get
            {
                return this.ID_SISTEMAField;
            }
            set
            {
                this.ID_SISTEMAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_TIPO_DOCUMENTO
        {
            get
            {
                return this.ID_TIPO_DOCUMENTOField;
            }
            set
            {
                this.ID_TIPO_DOCUMENTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_TIPO_PERSONA
        {
            get
            {
                return this.ID_TIPO_PERSONAField;
            }
            set
            {
                this.ID_TIPO_PERSONAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TIPO_USUARIO
        {
            get
            {
                return this.ID_TIPO_USUARIOField;
            }
            set
            {
                this.ID_TIPO_USUARIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRES
        {
            get
            {
                return this.NOMBRESField;
            }
            set
            {
                this.NOMBRESField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBSERVACION
        {
            get
            {
                return this.OBSERVACIONField;
            }
            set
            {
                this.OBSERVACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RAZON_SOCIAL
        {
            get
            {
                return this.RAZON_SOCIALField;
            }
            set
            {
                this.RAZON_SOCIALField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC
        {
            get
            {
                return this.RUCField;
            }
            set
            {
                this.RUCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_PersonaRepresentante RepresentanteLegal
        {
            get
            {
                return this.RepresentanteLegalField;
            }
            set
            {
                this.RepresentanteLegalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEFONO
        {
            get
            {
                return this.TELEFONOField;
            }
            set
            {
                this.TELEFONOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cls_Ent_PersonaRepresentante", Namespace="http://schemas.datacontract.org/2004/07/Capa_Entidad.Bitacora")]
    public partial class Cls_Ent_PersonaRepresentante : ServiceActiveDirectory.Cls_Ent_Base
    {
        
        private string APELLIDO_MATERNOField;
        
        private string APELLIDO_PATERNOField;
        
        private string CELULARField;
        
        private string CODIGO_DNIField;
        
        private string CORREOField;
        
        private string DIRECCIONField;
        
        private string DNIField;
        
        private int ID_LFField;
        
        private string ID_PERSONA_EXTERNAField;
        
        private int ID_TIPO_DOCUMENTOField;
        
        private string NOMBRESField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APELLIDO_MATERNO
        {
            get
            {
                return this.APELLIDO_MATERNOField;
            }
            set
            {
                this.APELLIDO_MATERNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APELLIDO_PATERNO
        {
            get
            {
                return this.APELLIDO_PATERNOField;
            }
            set
            {
                this.APELLIDO_PATERNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CELULAR
        {
            get
            {
                return this.CELULARField;
            }
            set
            {
                this.CELULARField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_DNI
        {
            get
            {
                return this.CODIGO_DNIField;
            }
            set
            {
                this.CODIGO_DNIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO
        {
            get
            {
                return this.CORREOField;
            }
            set
            {
                this.CORREOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DIRECCION
        {
            get
            {
                return this.DIRECCIONField;
            }
            set
            {
                this.DIRECCIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI
        {
            get
            {
                return this.DNIField;
            }
            set
            {
                this.DNIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_LF
        {
            get
            {
                return this.ID_LFField;
            }
            set
            {
                this.ID_LFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_PERSONA_EXTERNA
        {
            get
            {
                return this.ID_PERSONA_EXTERNAField;
            }
            set
            {
                this.ID_PERSONA_EXTERNAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TIPO_DOCUMENTO
        {
            get
            {
                return this.ID_TIPO_DOCUMENTOField;
            }
            set
            {
                this.ID_TIPO_DOCUMENTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRES
        {
            get
            {
                return this.NOMBRESField;
            }
            set
            {
                this.NOMBRESField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cls_Ent_Oficina", Namespace="http://schemas.datacontract.org/2004/07/Capa_Entidad.Bitacora")]
    public partial class Cls_Ent_Oficina : object
    {
        
        private string DESC_OFICINAField;
        
        private string ID_OFICINAField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESC_OFICINA
        {
            get
            {
                return this.DESC_OFICINAField;
            }
            set
            {
                this.DESC_OFICINAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_OFICINA
        {
            get
            {
                return this.ID_OFICINAField;
            }
            set
            {
                this.ID_OFICINAField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cls_Ent_Base", Namespace="http://schemas.datacontract.org/2004/07/Capa_Entidad")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_PersonaExterna))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_PersonaRepresentante))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_Usuario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceActiveDirectory.Cls_Ent_Sistemas_Modulos))]
    public partial class Cls_Ent_Base : object
    {
        
        private string ACCIONField;
        
        private string FEC_CREACIONField;
        
        private string FEC_MODIFICACIONField;
        
        private string FLG_ESTADOField;
        
        private string IP_CREACIONField;
        
        private string IP_MODIFICACIONField;
        
        private string USU_CREACIONField;
        
        private string USU_MODIFICACIONField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACCION
        {
            get
            {
                return this.ACCIONField;
            }
            set
            {
                this.ACCIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FEC_CREACION
        {
            get
            {
                return this.FEC_CREACIONField;
            }
            set
            {
                this.FEC_CREACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FEC_MODIFICACION
        {
            get
            {
                return this.FEC_MODIFICACIONField;
            }
            set
            {
                this.FEC_MODIFICACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FLG_ESTADO
        {
            get
            {
                return this.FLG_ESTADOField;
            }
            set
            {
                this.FLG_ESTADOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP_CREACION
        {
            get
            {
                return this.IP_CREACIONField;
            }
            set
            {
                this.IP_CREACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP_MODIFICACION
        {
            get
            {
                return this.IP_MODIFICACIONField;
            }
            set
            {
                this.IP_MODIFICACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USU_CREACION
        {
            get
            {
                return this.USU_CREACIONField;
            }
            set
            {
                this.USU_CREACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USU_MODIFICACION
        {
            get
            {
                return this.USU_MODIFICACIONField;
            }
            set
            {
                this.USU_MODIFICACIONField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cls_Ent_Usuario", Namespace="http://schemas.datacontract.org/2004/07/Capa_Entidad")]
    public partial class Cls_Ent_Usuario : ServiceActiveDirectory.Cls_Ent_Base
    {
        
        private string CLAVE_USUARIOField;
        
        private string COD_USUARIOField;
        
        private string DESC_OFICINAField;
        
        private string FECHA_ACTIVACIONField;
        
        private string FECHA_DESACTIVACIONField;
        
        private string FLG_ACTIVEDIRECTORYField;
        
        private string ID_OFICINAField;
        
        private int ID_PERFILField;
        
        private int ID_SISTEMAField;
        
        private int ID_TIPO_USUARIOField;
        
        private long ID_USUARIOField;
        
        private ServiceActiveDirectory.Cls_Ent_Perfil[] PerfilField;
        
        private ServiceActiveDirectory.Cls_Ent_Persona PersonaField;
        
        private string TOKENField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLAVE_USUARIO
        {
            get
            {
                return this.CLAVE_USUARIOField;
            }
            set
            {
                this.CLAVE_USUARIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_USUARIO
        {
            get
            {
                return this.COD_USUARIOField;
            }
            set
            {
                this.COD_USUARIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESC_OFICINA
        {
            get
            {
                return this.DESC_OFICINAField;
            }
            set
            {
                this.DESC_OFICINAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHA_ACTIVACION
        {
            get
            {
                return this.FECHA_ACTIVACIONField;
            }
            set
            {
                this.FECHA_ACTIVACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHA_DESACTIVACION
        {
            get
            {
                return this.FECHA_DESACTIVACIONField;
            }
            set
            {
                this.FECHA_DESACTIVACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FLG_ACTIVEDIRECTORY
        {
            get
            {
                return this.FLG_ACTIVEDIRECTORYField;
            }
            set
            {
                this.FLG_ACTIVEDIRECTORYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_OFICINA
        {
            get
            {
                return this.ID_OFICINAField;
            }
            set
            {
                this.ID_OFICINAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PERFIL
        {
            get
            {
                return this.ID_PERFILField;
            }
            set
            {
                this.ID_PERFILField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_SISTEMA
        {
            get
            {
                return this.ID_SISTEMAField;
            }
            set
            {
                this.ID_SISTEMAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TIPO_USUARIO
        {
            get
            {
                return this.ID_TIPO_USUARIOField;
            }
            set
            {
                this.ID_TIPO_USUARIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID_USUARIO
        {
            get
            {
                return this.ID_USUARIOField;
            }
            set
            {
                this.ID_USUARIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_Perfil[] Perfil
        {
            get
            {
                return this.PerfilField;
            }
            set
            {
                this.PerfilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_Persona Persona
        {
            get
            {
                return this.PersonaField;
            }
            set
            {
                this.PersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TOKEN
        {
            get
            {
                return this.TOKENField;
            }
            set
            {
                this.TOKENField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cls_Ent_Perfil", Namespace="http://schemas.datacontract.org/2004/07/Capa_Entidad")]
    public partial class Cls_Ent_Perfil : object
    {
        
        private string DESC_OFICINAField;
        
        private string DESC_PERFILField;
        
        private string ID_OFICINAField;
        
        private int ID_PERFILField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESC_OFICINA
        {
            get
            {
                return this.DESC_OFICINAField;
            }
            set
            {
                this.DESC_OFICINAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESC_PERFIL
        {
            get
            {
                return this.DESC_PERFILField;
            }
            set
            {
                this.DESC_PERFILField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_OFICINA
        {
            get
            {
                return this.ID_OFICINAField;
            }
            set
            {
                this.ID_OFICINAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PERFIL
        {
            get
            {
                return this.ID_PERFILField;
            }
            set
            {
                this.ID_PERFILField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cls_Ent_Solicitud_Usuario_Login", Namespace="http://schemas.datacontract.org/2004/07/Capa_Entidad")]
    public partial class Cls_Ent_Solicitud_Usuario_Login : object
    {
        
        private string COD_USUARIOField;
        
        private bool EXPIRADOField;
        
        private string FEC_CREACIONField;
        
        private long IDField;
        
        private long ID_SISTEMA_ACTUALField;
        
        private long ID_SISTEMA_REDIRIGIRField;
        
        private long ID_USUARIOField;
        
        private string IP_CREACIONField;
        
        private short MINUTOS_EXPIRAField;
        
        private string SISTEMA_REDIRIGIR_DESCField;
        
        private string URL_SISTEMAField;
        
        private string USU_CREACIONField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_USUARIO
        {
            get
            {
                return this.COD_USUARIOField;
            }
            set
            {
                this.COD_USUARIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EXPIRADO
        {
            get
            {
                return this.EXPIRADOField;
            }
            set
            {
                this.EXPIRADOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FEC_CREACION
        {
            get
            {
                return this.FEC_CREACIONField;
            }
            set
            {
                this.FEC_CREACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID_SISTEMA_ACTUAL
        {
            get
            {
                return this.ID_SISTEMA_ACTUALField;
            }
            set
            {
                this.ID_SISTEMA_ACTUALField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID_SISTEMA_REDIRIGIR
        {
            get
            {
                return this.ID_SISTEMA_REDIRIGIRField;
            }
            set
            {
                this.ID_SISTEMA_REDIRIGIRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID_USUARIO
        {
            get
            {
                return this.ID_USUARIOField;
            }
            set
            {
                this.ID_USUARIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP_CREACION
        {
            get
            {
                return this.IP_CREACIONField;
            }
            set
            {
                this.IP_CREACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short MINUTOS_EXPIRA
        {
            get
            {
                return this.MINUTOS_EXPIRAField;
            }
            set
            {
                this.MINUTOS_EXPIRAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SISTEMA_REDIRIGIR_DESC
        {
            get
            {
                return this.SISTEMA_REDIRIGIR_DESCField;
            }
            set
            {
                this.SISTEMA_REDIRIGIR_DESCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL_SISTEMA
        {
            get
            {
                return this.URL_SISTEMAField;
            }
            set
            {
                this.URL_SISTEMAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USU_CREACION
        {
            get
            {
                return this.USU_CREACIONField;
            }
            set
            {
                this.USU_CREACIONField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaSeguridadU", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Seguridad")]
    public partial class RespuestaSeguridadU : object
    {
        
        private ServiceActiveDirectory.Cls_Ent_Auditoria AuditoriaField;
        
        private ServiceActiveDirectory.Cls_Ent_Usuario UsuarioField;
        
        private bool Usuario_ValidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_Auditoria Auditoria
        {
            get
            {
                return this.AuditoriaField;
            }
            set
            {
                this.AuditoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_Usuario Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Usuario_Valido
        {
            get
            {
                return this.Usuario_ValidoField;
            }
            set
            {
                this.Usuario_ValidoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaAuditoria", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Seguridad")]
    public partial class RespuestaAuditoria : object
    {
        
        private ServiceActiveDirectory.Cls_Ent_Auditoria AuditoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_Auditoria Auditoria
        {
            get
            {
                return this.AuditoriaField;
            }
            set
            {
                this.AuditoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaSeguridadID", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Seguridad")]
    public partial class RespuestaSeguridadID : object
    {
        
        private long ID_USUARIOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID_USUARIO
        {
            get
            {
                return this.ID_USUARIOField;
            }
            set
            {
                this.ID_USUARIOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaSeguridadBool", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Seguridad")]
    public partial class RespuestaSeguridadBool : object
    {
        
        private bool ValidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valido
        {
            get
            {
                return this.ValidoField;
            }
            set
            {
                this.ValidoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeguridadArchivo", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Seguridad")]
    public partial class SeguridadArchivo : object
    {
        
        private byte[] ARCHIVOField;
        
        private string NOMBRE_ARCHIVOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ARCHIVO
        {
            get
            {
                return this.ARCHIVOField;
            }
            set
            {
                this.ARCHIVOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE_ARCHIVO
        {
            get
            {
                return this.NOMBRE_ARCHIVOField;
            }
            set
            {
                this.NOMBRE_ARCHIVOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaPerfil", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Seguridad")]
    public partial class RespuestaPerfil : object
    {
        
        private ServiceActiveDirectory.Cls_Ent_Auditoria AuditoriaField;
        
        private ServiceActiveDirectory.Cls_Ent_Perfil[] PerfilesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_Auditoria Auditoria
        {
            get
            {
                return this.AuditoriaField;
            }
            set
            {
                this.AuditoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_Perfil[] Perfiles
        {
            get
            {
                return this.PerfilesField;
            }
            set
            {
                this.PerfilesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaOficina", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Seguridad")]
    public partial class RespuestaOficina : object
    {
        
        private ServiceActiveDirectory.Cls_Ent_Auditoria AuditoriaField;
        
        private ServiceActiveDirectory.Cls_Ent_Oficina[] OficinasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_Auditoria Auditoria
        {
            get
            {
                return this.AuditoriaField;
            }
            set
            {
                this.AuditoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_Oficina[] Oficinas
        {
            get
            {
                return this.OficinasField;
            }
            set
            {
                this.OficinasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaSolicitudLogin", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Seguridad")]
    public partial class RespuestaSolicitudLogin : object
    {
        
        private ServiceActiveDirectory.Cls_Ent_Auditoria AuditoriaField;
        
        private ServiceActiveDirectory.Cls_Ent_Solicitud_Usuario_Login SolicitudField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_Auditoria Auditoria
        {
            get
            {
                return this.AuditoriaField;
            }
            set
            {
                this.AuditoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_Solicitud_Usuario_Login Solicitud
        {
            get
            {
                return this.SolicitudField;
            }
            set
            {
                this.SolicitudField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaSolicitudLoginRegistro", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Seguridad")]
    public partial class RespuestaSolicitudLoginRegistro : object
    {
        
        private ServiceActiveDirectory.Cls_Ent_Auditoria AuditoriaField;
        
        private long SolicitudIdField;
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceActiveDirectory.Cls_Ent_Auditoria Auditoria
        {
            get
            {
                return this.AuditoriaField;
            }
            set
            {
                this.AuditoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SolicitudId
        {
            get
            {
                return this.SolicitudIdField;
            }
            set
            {
                this.SolicitudIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceActiveDirectory.ISWLogin")]
    public interface ISWLogin
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Usuario_ObtenerModulos", ReplyAction="http://tempuri.org/ISWLogin/Usuario_ObtenerModulosResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadM> Usuario_ObtenerModulosAsync(string TOKEN, int ID_SISTEMA, string ID_PERFIL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Usuario_Login", ReplyAction="http://tempuri.org/ISWLogin/Usuario_LoginResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadU> Usuario_LoginAsync(string USUARIO, string CLAVE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/UsuarioLoginAD", ReplyAction="http://tempuri.org/ISWLogin/UsuarioLoginADResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadU> UsuarioLoginADAsync(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/UsuarioValidarAD", ReplyAction="http://tempuri.org/ISWLogin/UsuarioValidarADResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadU> UsuarioValidarADAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/UsuarioActiveDirectory_Login1", ReplyAction="http://tempuri.org/ISWLogin/UsuarioActiveDirectory_Login1Response")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadU> UsuarioActiveDirectory_Login1Async(string USUARIO, string CLAVE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/UsuarioActiveDirectory_Login2", ReplyAction="http://tempuri.org/ISWLogin/UsuarioActiveDirectory_Login2Response")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadU> UsuarioActiveDirectory_Login2Async(string USUARIO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Usuario_Sistema", ReplyAction="http://tempuri.org/ISWLogin/Usuario_SistemaResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadU> Usuario_SistemaAsync(string TOKEN, int ID_SISTEMA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Usuario_Eliminar", ReplyAction="http://tempuri.org/ISWLogin/Usuario_EliminarResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_EliminarAsync(long ID_USUARIO, int ID_SISTEMA, string USU_MODIFICACION, string IP_MODIFICACION);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Usuario_Estado", ReplyAction="http://tempuri.org/ISWLogin/Usuario_EstadoResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_EstadoAsync(long ID_USUARIO, int ID_SISTEMA, string FLG_ESTADO, string USU_MODIFICACION, string IP_MODIFICACION);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Usuario_Insertar", ReplyAction="http://tempuri.org/ISWLogin/Usuario_InsertarResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_InsertarAsync(ServiceActiveDirectory.Cls_Ent_Usuario entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Usuario_Actualizar", ReplyAction="http://tempuri.org/ISWLogin/Usuario_ActualizarResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_ActualizarAsync(ServiceActiveDirectory.Cls_Ent_Usuario entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Usuario_ActualizarActivacion", ReplyAction="http://tempuri.org/ISWLogin/Usuario_ActualizarActivacionResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_ActualizarActivacionAsync(long ID_USUARIO, int ID_SISTEMA, string FECHA_ACTIVACION, string FECHA_DESACTIVACION, string USU_MODIFICACION, string IP_MODIFICACION);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Obtener_Id_Usuario", ReplyAction="http://tempuri.org/ISWLogin/Obtener_Id_UsuarioResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadID> Obtener_Id_UsuarioAsync(string TOKEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Obtener_Cod_Usuario", ReplyAction="http://tempuri.org/ISWLogin/Obtener_Cod_UsuarioResponse")]
        System.Threading.Tasks.Task<string> Obtener_Cod_UsuarioAsync(string TOKEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Obtener_Id_Persona", ReplyAction="http://tempuri.org/ISWLogin/Obtener_Id_PersonaResponse")]
        System.Threading.Tasks.Task<string> Obtener_Id_PersonaAsync(string TOKEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Validar_Token", ReplyAction="http://tempuri.org/ISWLogin/Validar_TokenResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadBool> Validar_TokenAsync(string TOKEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Encriptar", ReplyAction="http://tempuri.org/ISWLogin/EncriptarResponse")]
        System.Threading.Tasks.Task<string> EncriptarAsync(string CODIGO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Usuario_ActualizarClave", ReplyAction="http://tempuri.org/ISWLogin/Usuario_ActualizarClaveResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_ActualizarClaveAsync(string TOKEN, string CLAVE_USUARIO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Usuario_PedirClave", ReplyAction="http://tempuri.org/ISWLogin/Usuario_PedirClaveResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_PedirClaveAsync(string TOKEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Usuario_OlvidoClave", ReplyAction="http://tempuri.org/ISWLogin/Usuario_OlvidoClaveResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_OlvidoClaveAsync(string CORREO, string CODIGO, string USU_CREACION, string IP_CREACION);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Usuario_VerificaCodigo", ReplyAction="http://tempuri.org/ISWLogin/Usuario_VerificaCodigoResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_VerificaCodigoAsync(string TOKEN, string CODIGO, string USU_MODIFICACION, string IP_MODIFICACION);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/PersonaExterna_Insertar", ReplyAction="http://tempuri.org/ISWLogin/PersonaExterna_InsertarResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> PersonaExterna_InsertarAsync(ServiceActiveDirectory.Cls_Ent_PersonaExterna entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/PersonaExterna_Validar", ReplyAction="http://tempuri.org/ISWLogin/PersonaExterna_ValidarResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> PersonaExterna_ValidarAsync(string ID_PERSONA, int ID_SISTEMA, int ID_TIPO_USUARIO, string FLG_VALIDO, string OBSERVACION, string USU_CREACION, string IP_CREACION);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Laser_Importar", ReplyAction="http://tempuri.org/ISWLogin/Laser_ImportarResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Laser_ImportarAsync(string IP, string SERVIDOR, string VOLUMEN, string CARPETA, string USUARIO, string CLAVE, string[] CARPETAS, ServiceActiveDirectory.SeguridadArchivo MIARCHIVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Laser_Exportar", ReplyAction="http://tempuri.org/ISWLogin/Laser_ExportarResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Laser_ExportarAsync(string IP, string SERVIDOR, string USUARIO, string CLAVE, int ID_LF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Perfil_Listar", ReplyAction="http://tempuri.org/ISWLogin/Perfil_ListarResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaPerfil> Perfil_ListarAsync(string ID_SISTEMA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Usuario_Perfiles_Listar", ReplyAction="http://tempuri.org/ISWLogin/Usuario_Perfiles_ListarResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaPerfil> Usuario_Perfiles_ListarAsync(long ID_USUARIO, int ID_SISTEMA, string ID_OFICINA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Usuario_Oficinas_Listar", ReplyAction="http://tempuri.org/ISWLogin/Usuario_Oficinas_ListarResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaOficina> Usuario_Oficinas_ListarAsync(string ID_PERSONA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Solicitud_Login", ReplyAction="http://tempuri.org/ISWLogin/Solicitud_LoginResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSolicitudLogin> Solicitud_LoginAsync(long id, long usuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Solicitud_Registrar", ReplyAction="http://tempuri.org/ISWLogin/Solicitud_RegistrarResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSolicitudLoginRegistro> Solicitud_RegistrarAsync(ServiceActiveDirectory.Cls_Ent_Solicitud_Usuario_Login entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Solicitud_Validar", ReplyAction="http://tempuri.org/ISWLogin/Solicitud_ValidarResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadBool> Solicitud_ValidarAsync(long id, long usuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWLogin/Solicitud_Expirar", ReplyAction="http://tempuri.org/ISWLogin/Solicitud_ExpirarResponse")]
        System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadBool> Solicitud_ExpirarAsync(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ISWLoginChannel : ServiceActiveDirectory.ISWLogin, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SWLoginClient : System.ServiceModel.ClientBase<ServiceActiveDirectory.ISWLogin>, ServiceActiveDirectory.ISWLogin
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SWLoginClient(EndpointConfiguration endpointConfiguration) : 
                base(SWLoginClient.GetBindingForEndpoint(endpointConfiguration), SWLoginClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SWLoginClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SWLoginClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SWLoginClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SWLoginClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SWLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadM> Usuario_ObtenerModulosAsync(string TOKEN, int ID_SISTEMA, string ID_PERFIL)
        {
            return base.Channel.Usuario_ObtenerModulosAsync(TOKEN, ID_SISTEMA, ID_PERFIL);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadU> Usuario_LoginAsync(string USUARIO, string CLAVE)
        {
            return base.Channel.Usuario_LoginAsync(USUARIO, CLAVE);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadU> UsuarioLoginADAsync(string usuario, string clave)
        {
            return base.Channel.UsuarioLoginADAsync(usuario, clave);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadU> UsuarioValidarADAsync(string usuario)
        {
            return base.Channel.UsuarioValidarADAsync(usuario);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadU> UsuarioActiveDirectory_Login1Async(string USUARIO, string CLAVE)
        {
            return base.Channel.UsuarioActiveDirectory_Login1Async(USUARIO, CLAVE);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadU> UsuarioActiveDirectory_Login2Async(string USUARIO)
        {
            return base.Channel.UsuarioActiveDirectory_Login2Async(USUARIO);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadU> Usuario_SistemaAsync(string TOKEN, int ID_SISTEMA)
        {
            return base.Channel.Usuario_SistemaAsync(TOKEN, ID_SISTEMA);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_EliminarAsync(long ID_USUARIO, int ID_SISTEMA, string USU_MODIFICACION, string IP_MODIFICACION)
        {
            return base.Channel.Usuario_EliminarAsync(ID_USUARIO, ID_SISTEMA, USU_MODIFICACION, IP_MODIFICACION);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_EstadoAsync(long ID_USUARIO, int ID_SISTEMA, string FLG_ESTADO, string USU_MODIFICACION, string IP_MODIFICACION)
        {
            return base.Channel.Usuario_EstadoAsync(ID_USUARIO, ID_SISTEMA, FLG_ESTADO, USU_MODIFICACION, IP_MODIFICACION);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_InsertarAsync(ServiceActiveDirectory.Cls_Ent_Usuario entidad)
        {
            return base.Channel.Usuario_InsertarAsync(entidad);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_ActualizarAsync(ServiceActiveDirectory.Cls_Ent_Usuario entidad)
        {
            return base.Channel.Usuario_ActualizarAsync(entidad);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_ActualizarActivacionAsync(long ID_USUARIO, int ID_SISTEMA, string FECHA_ACTIVACION, string FECHA_DESACTIVACION, string USU_MODIFICACION, string IP_MODIFICACION)
        {
            return base.Channel.Usuario_ActualizarActivacionAsync(ID_USUARIO, ID_SISTEMA, FECHA_ACTIVACION, FECHA_DESACTIVACION, USU_MODIFICACION, IP_MODIFICACION);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadID> Obtener_Id_UsuarioAsync(string TOKEN)
        {
            return base.Channel.Obtener_Id_UsuarioAsync(TOKEN);
        }
        
        public System.Threading.Tasks.Task<string> Obtener_Cod_UsuarioAsync(string TOKEN)
        {
            return base.Channel.Obtener_Cod_UsuarioAsync(TOKEN);
        }
        
        public System.Threading.Tasks.Task<string> Obtener_Id_PersonaAsync(string TOKEN)
        {
            return base.Channel.Obtener_Id_PersonaAsync(TOKEN);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadBool> Validar_TokenAsync(string TOKEN)
        {
            return base.Channel.Validar_TokenAsync(TOKEN);
        }
        
        public System.Threading.Tasks.Task<string> EncriptarAsync(string CODIGO)
        {
            return base.Channel.EncriptarAsync(CODIGO);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_ActualizarClaveAsync(string TOKEN, string CLAVE_USUARIO)
        {
            return base.Channel.Usuario_ActualizarClaveAsync(TOKEN, CLAVE_USUARIO);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_PedirClaveAsync(string TOKEN)
        {
            return base.Channel.Usuario_PedirClaveAsync(TOKEN);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_OlvidoClaveAsync(string CORREO, string CODIGO, string USU_CREACION, string IP_CREACION)
        {
            return base.Channel.Usuario_OlvidoClaveAsync(CORREO, CODIGO, USU_CREACION, IP_CREACION);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Usuario_VerificaCodigoAsync(string TOKEN, string CODIGO, string USU_MODIFICACION, string IP_MODIFICACION)
        {
            return base.Channel.Usuario_VerificaCodigoAsync(TOKEN, CODIGO, USU_MODIFICACION, IP_MODIFICACION);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> PersonaExterna_InsertarAsync(ServiceActiveDirectory.Cls_Ent_PersonaExterna entidad)
        {
            return base.Channel.PersonaExterna_InsertarAsync(entidad);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> PersonaExterna_ValidarAsync(string ID_PERSONA, int ID_SISTEMA, int ID_TIPO_USUARIO, string FLG_VALIDO, string OBSERVACION, string USU_CREACION, string IP_CREACION)
        {
            return base.Channel.PersonaExterna_ValidarAsync(ID_PERSONA, ID_SISTEMA, ID_TIPO_USUARIO, FLG_VALIDO, OBSERVACION, USU_CREACION, IP_CREACION);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Laser_ImportarAsync(string IP, string SERVIDOR, string VOLUMEN, string CARPETA, string USUARIO, string CLAVE, string[] CARPETAS, ServiceActiveDirectory.SeguridadArchivo MIARCHIVO)
        {
            return base.Channel.Laser_ImportarAsync(IP, SERVIDOR, VOLUMEN, CARPETA, USUARIO, CLAVE, CARPETAS, MIARCHIVO);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaAuditoria> Laser_ExportarAsync(string IP, string SERVIDOR, string USUARIO, string CLAVE, int ID_LF)
        {
            return base.Channel.Laser_ExportarAsync(IP, SERVIDOR, USUARIO, CLAVE, ID_LF);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaPerfil> Perfil_ListarAsync(string ID_SISTEMA)
        {
            return base.Channel.Perfil_ListarAsync(ID_SISTEMA);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaPerfil> Usuario_Perfiles_ListarAsync(long ID_USUARIO, int ID_SISTEMA, string ID_OFICINA)
        {
            return base.Channel.Usuario_Perfiles_ListarAsync(ID_USUARIO, ID_SISTEMA, ID_OFICINA);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaOficina> Usuario_Oficinas_ListarAsync(string ID_PERSONA)
        {
            return base.Channel.Usuario_Oficinas_ListarAsync(ID_PERSONA);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSolicitudLogin> Solicitud_LoginAsync(long id, long usuarioId)
        {
            return base.Channel.Solicitud_LoginAsync(id, usuarioId);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSolicitudLoginRegistro> Solicitud_RegistrarAsync(ServiceActiveDirectory.Cls_Ent_Solicitud_Usuario_Login entidad)
        {
            return base.Channel.Solicitud_RegistrarAsync(entidad);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadBool> Solicitud_ValidarAsync(long id, long usuarioId)
        {
            return base.Channel.Solicitud_ValidarAsync(id, usuarioId);
        }
        
        public System.Threading.Tasks.Task<ServiceActiveDirectory.RespuestaSeguridadBool> Solicitud_ExpirarAsync(long id)
        {
            return base.Channel.Solicitud_ExpirarAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISWLogin))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ISWLogin))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISWLogin))
            {
                return new System.ServiceModel.EndpointAddress("http://srvstd.ingemmet.int/WS_Seguridad/SWLogin.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ISWLogin))
            {
                return new System.ServiceModel.EndpointAddress("https://srvstd.ingemmet.gob.pe/WS_Seguridad/SWLogin.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISWLogin,
            
            BasicHttpsBinding_ISWLogin,
        }
    }
}
