name: SonarQube Analysis

on:
  push:
    branches:
      - develop  # Se ejecutar치 en cada push a 'develop'
  pull_request:
    branches:
      - develop  # Se ejecutar치 en PR hacia 'develop'

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c칩digo
        uses: actions/checkout@v4

      - name: Configurar .NET (para proyectos C#)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x  # Ajusta a la versi칩n de tu proyecto

      - name: Instalar SonarScanner para .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Ejecutar SonarQube Scanner (C#)
        run: |
          dotnet-sonarscanner begin /k:"GIS-System" \
          /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          dotnet build
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Ejecutar SonarQube Scanner (Python)
        run: |
          sonar-scanner \
          -Dsonar.projectKey=GIS-System \
          -Dsonar.source
